---

- name: configure nginx
  become: true
  template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream/http_fxa_oauth.conf
  notify: reload nginx config

- name: create shared mount point for configuration info
  file: path=/data/config/oauth state=directory owner=app group=app mode=0777
  become: true

- name: configure fxa-oauth-server
  become: true
  template: src=config.json.j2 dest=/data/config/oauth/local.json

- name: pull oauth docker image
  become: true
  docker_image:
    # pull image always. In a pending update to ansible, it will only set
    # changed:true if the image has actually changed. However, docker_container
    # `state:started` will only re-start if image of configuration has
    # changed.
    force: true
    state: present
    name: mozilla/fxa-oauth-server
    tag: "{{ oauth_docker_tag }}"
  register: image

- debug: var=image

- name: Start oauth docker container
  become: true
  docker_container:
    name: oauth
    image: mozilla/fxa-oauth-server{{ ':' + oauth_docker_tag }} 
    state: started
    network_mode: host
    ports:
      - 9010:9010
    command: node bin/server.js
    env:
      CONFIG_FILES: "/config/local.json"
    volumes:
      - /data/config/oauth:/config:ro
  register: container

- debug: var=container

- name: Start oauth-internal docker container
  become: true
  docker_container:
    name: oauth-internal
    image: mozilla/fxa-oauth-server{{ ':' + oauth_docker_tag }}
    state: started
    network_mode: host
    ports:
      - 9111:9111
    command: node bin/server.js
    env:
      # The oauth and oauth-internal containers can race to create the `oauth`
      # database on first run. So, have the oauth-internal container skip
      # schema creation and just rely on the main oauth server to do so.
      CREATE_MYSQL_SCHEMA: "false"
      CONFIG_FILES: "/config/local.json"
    volumes:
      - /data/config/oauth:/config:ro
  register: container

- debug: var=container

- meta: flush_handlers
