---

- name: configure nginx
  become: true
  template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream/http_fxa_oauth.conf
  notify: reload nginx config

- name: create shared mount point for configuration info
  file: path=/data/config/oauth state=directory owner=app group=app mode=0777
  become: true

- name: configure fxa-oauth-server
  become: true
  template: src=config.json.j2 dest=/data/config/oauth/local.json

- name: pull oauth docker image
  become: true
  docker_image:
    # pull image always. In a pending update to ansible, it will only set
    # changed:true if the image has actually changed. However, docker_container
    # `state:started` will only re-start if image of configuration has
    # changed.
    force: true
    state: present
    name: mozilla/fxa-oauth-server
    tag: "{{ oauth_docker_tag }}"
  register: image

- debug: var=image

- name: Start oauth docker container
  become: true
  docker_container:
    # See note in https://github.com/mozilla/fxa-dev/tree/docker#about-using-docker_container-and-semi-mandatory-quoting
    name: oauth
    image: mozilla/fxa-oauth-server{{ ':' + oauth_docker_tag }}
    state: "{{ oauth_docker_state }}"
    network_mode: host
    ports:
      - 9010:9010
    command: node fxa-oauth-server/bin/server.js
    env:
      VERIFICATION_URL: http://127.0.0.1:8005/v2
      CONFIG_FILES: "/config/local.json"
    volumes:
      - /data/config/oauth:/config:ro
  register: container

- debug: var=container

- meta: flush_handlers
