---

- name: configure nginx upstream
  become: true
  template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream/http_fxa-rp-untrusted.conf
  notify: reload nginx config

- name: create shared mount point for configuration info
  file: path=/data/config/rp-untrusted state=directory owner=app group=app mode=0777
  become: true

- name: configure fxa-rp
  become: true
  become_user: app
  template: src=config.json.j2 dest=/data/config/rp-untrusted/config-dev.json

- name: pull 123done docker image
  become: true
  docker_image:
    # pull image always. In a pending update to ansible, it will only set
    # changed:true if the image has actually changed. However, docker_container
    # `state:started` will only re-start if image of configuration has
    # changed.
    force: true
    state: present
    name: mozilla/123done
    tag: "{{ rp_docker_tag }}"
  register: image

- debug: var=image

# Note: container renamed to `rp2-untrusted` so that existing fxa-dev boxes
# will remove the currently running container named `rp-untrusted` and
# `rp2-untrusted` will not fail to bind on the listening tcp port number.

- name: Ensure removal of existing `rp-untrusted` container.
  become: true
  docker_container:
    # See note in https://github.com/mozilla/fxa-dev/tree/docker#about-using-docker_container-and-semi-mandatory-quoting
    name: rp-untrusted
    state: absent

- name: Start 123done docker container as rp2-untrusted
  become: true
  docker_container:
    # See note in https://github.com/mozilla/fxa-dev/tree/docker#about-using-docker_container-and-semi-mandatory-quoting
    name: rp2-untrusted
    image: mozilla/123done{{ ':' + rp_untrusted_docker_tag }}
    state: "{{ rp_untrusted_docker_state }}"
    network_mode: host
    ports:
      - 4902:4902
    command: node ./server.js
    env:
      CONFIG_123DONE: "/config/config-dev.json"
    volumes:
      - /data/config/rp-untrusted:/config
  register: container

- debug: var=container

- meta: flush_handlers
