---

- name: create app user
  sudo: true
  user: name=app state=present

- name: update installed packages
  sudo: true
  yum: name=* state=latest

- name: install base packages
  sudo: true
  yum: name={{ item }} state=present
  with_items:
    - gcc-c++
    - git
    - ntp
    - python-pip

- name: install nave
  sudo: true
  get_url: url=https://raw.githubusercontent.com/isaacs/nave/master/nave.sh
           dest=/usr/local/bin/nave
           mode=755

- name: install node
  sudo: true
  # there's an npm bug somewhere between 1.4.3 and 1.4.9 that breaks the
  # content-server install, so use the older node for now
  command: /usr/local/bin/nave usemain 0.10.26
  register: nave_out
  # TODO detect actual changes
  changed_when: false

- file: src=/usr/local/bin/node dest=/usr/bin/node state=link
  sudo: true
- file: src=/usr/local/bin/npm dest=/usr/bin/npm state=link
  sudo: true

- name: install supervisord
  sudo: true
  pip: name=supervisor version=3.0 state=present

- file: path=/etc/supervisor.d state=directory
  sudo: true

- file: path=/data state=directory owner=app group=app mode=0777
  sudo: true

- name: upstart or systemd?
  sudo: true
  command: which initctl
  failed_when: false
  changed_when: false
  register: is_upstart

- name: upstart supervisord
  sudo: true
  copy: src=supervisor.conf dest=/etc/init/supervisor.conf owner=root group=root
  when: is_upstart.rc == 0

- name: systemd supervisord
  sudo: true
  copy: src=supervisor.systemd dest=/etc/systemd/system/supervisor.service owner=root group=root
  when: is_upstart.rc != 0

- name: configure supervisord
  sudo: true
  copy: src=supervisord.conf dest=/etc/supervisord.conf owner=root group=root
  notify: restart supervisor

- name: start supervisord
  sudo: true
  service: name=supervisor state=started

- name: install heka
  sudo: true
  yum: name=https://dl.dropboxusercontent.com/u/3684283/heka-0_6_0-linux-amd64.rpm state=present

- file: path=/etc/heka.d state=directory
  sudo: true

- name: supervise heka
  sudo: true
  copy: src=hekad.conf dest=/etc/supervisor.d/hekad.conf
  notify: update supervisor

- name: configure heka
  sudo: true
  copy: src=hekad.toml dest=/etc/heka.d/!hekad.toml
  notify: restart heka

- name: configure ntp
  sudo: true
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntp

- name: start ntp
  sudo: true
  service: name=ntpd state=started enabled=true

- meta: flush_handlers
