---

- name: create app user
  become: true
  user: name=app state=present append=yes

- name: update installed packages
  become: true
  yum:
    name: '*'
    state: latest
    use_backend: yum

- name: install base packages
  become: true
  yum:
    name: "{{ item }}"
    state: present
    use_backend: yum
  with_items:
    - docker
    - gcc-c++
    - git
    - ntp
    - python-dnf

- name: update installed packages
  become: true
  yum: name=* state=latest

- name: ensure a docker group is created to allow running without sudo
  become: true
  group: name=docker state=present

- name: add ec2-user to the docker group
  become: true
  user: name=ec2-user append=yes groups=docker

# use extra_args to ensure ansible-playbook in in /usr/bin so cron can find it
- name: install ansible
  become: true
  pip: name=ansible state=present extra_args='--install-option="--install-scripts=/usr/bin"'

- name: install docker python module
  become: true
  pip: name=docker state=present

# for mounting configuration information in subdirectories under /data/config
# XXX fix mode/ownership
- file: path=/data/config state=directory owner=app group=app mode=0777
  become: true

- name: configure ntp
  become: true
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntp

- name: start ntp
  become: true
  service: name=ntpd state=started enabled=true

- name: start docker
  become: true
  service: name=docker state=started enabled=true

- meta: flush_handlers
