---

- name: create app user
  become: true
  user: name=app state=present append=yes

- name: update installed packages
  become: true
  yum: name=* state=latest

- name: install base packages
  become: true
  yum: name={{ item }} state=present
  with_items:
    - docker
    - gcc-c++
    - git
    - ntp
    - python-pip

- name: ensure a docker group is created to allow running without sudo
  become: true
  group: name=docker state=present

- name: add ec2-user to the docker group
  become: true
  user: name=ec2-user append=yes groups=docker

- name: install docker-py module
  become: true
  pip: name=docker-py state=present

# for mounting configuration information in subdirectories under /data/config
# XXX fix mode/ownership
- file: path=/data/config state=directory owner=app group=app mode=0777
  become: true

- name: configure ntp
  become: true
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntp

- name: start ntp
  become: true
  service: name=ntpd state=started enabled=true

- name: start docker
  become: true
  service: name=docker state=started enabled=true

- meta: flush_handlers
