---

- name: configure nginx upstream
  sudo: true
  template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream/http_syncserver.conf
  notify: reload nginx config

- name: configure nginx location
  sudo: true
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/location/http_syncserver.conf
  notify: reload nginx config

- name: install python build environment
  sudo: true
  yum: name=python-devel state=present

- name: install mysql command-line tools
  sudo: true
  yum: name=mysql

- name: install syncserver build dependencies
  sudo: true
  pip: name=virtualenv state=present

- name: create syncserver database
  sudo: true
  command: mysql --host={{ sync_db_host }} --user=root --password={{ sync_db_password }} -e "CREATE DATABASE IF NOT EXISTS sync"

- name: install syncserver
  tags: code
  sudo: true
  sudo_user: app
  git: repo={{ sync_git_repo }}
       dest=/data/syncserver
       version={{ sync_git_version }}
       force=true
  notify:
    - build syncserver virtualenv
    - restart syncserver process

- name: supervise syncserver
  sudo: true
  copy: src=syncserver.conf dest=/etc/supervisor.d/syncserver.conf
  notify: update supervisor

- name: configure syncserver
  sudo: true
  sudo_user: app
  template: src=syncserver.ini.j2 dest=/data/syncserver/syncserver.dev.ini
  notify: restart syncserver process

- meta: flush_handlers
